eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
server:
  port: 8080
spring:
  application:
    name: user-service
  zipkin :
    base-url :  http://localhost:9010
  rabbitmq:
    host : localhost
    port : 5672
    username : guest
    password : guest
userServiceVariable : userServiceVariable
management:
  security:
    enabled: false


