eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
server:
  port: 8080
spring:
  application:
    name: user-service
  zipkin :
    base-url :  http://localhost:8010
userServiceVariable : userServiceVariable
        
