eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
server:
  port: 8090
spring:
  application:
    name: user-controller
feign:
  hystrix:
    enabled : true
hystrix:
  metrics:
    polling-interval-ms: 500